apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: main
        image: nginx:1.25.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"   # Yêu cầu bộ nhớ tối thiểu
            cpu: "250m"      # Yêu cầu CPU tối thiểu
          limits:
            memory: "128Mi"  # Giới hạn bộ nhớ tối đa
            cpu: "500m"      # Giới hạn CPU tối đa
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  labels:
    app: nginx-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      # selectPolicy: Disabled
      stabilizationWindowSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx2-deployment  # Chọn các Pod có label app: nginx
  ports:
    - protocol: TCP
      port: 80        # Cổng mà Service sẽ lắng nghe
      targetPort: 80   # Cổng mà Container sẽ nhận
  type: ClusterIP      # Đây là loại Service mặc định, chỉ truy cập được trong cluster
---